add method climatology
imk-toolkit/imk-toolkit pull request #60
Opened 2022-03-03 15:16 UTC by fabrivelas

changed method anomaly to use the new method climatology
Please check

2022-03-03 16:06 UTC, ucyo requested changes

2022-03-03 16:06 UTC, ucyo commented on imktk/dataarray_methods/anomalies.py
> +    anomalies = dataarray.groupby("time.month") - climatology(dataarray)
Trying to execute this code returns the following error:

```sh
>>> t.imktk.anomalies()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python/imktk/toolkit.py", line 54, in method
    return func(accessor._data, *args, **kwargs)
  File "/home/python/imktk/dataarray_methods/anomalies.py", line 11, in main
    anomalies = dataarray.groupby("time.month") - climatology(dataarray)
TypeError: 'module' object is not callable
```
Which reminds me of doing a proper testing environment: Related #38

2022-03-03 16:08 UTC, ucyo commented on imktk/dataarray_methods/anomalies.py
> +    anomalies = dataarray.groupby("time.month") - climatology(dataarray)
Related #18

2022-03-03 16:08 UTC, ucyo commented
Related #18

2022-03-03 18:30 UTC, fabrivelas commented on imktk/dataarray_methods/anomalies.py
> +    anomalies = dataarray.groupby("time.month") - climatology(dataarray)
Did I do something wrong, here?

2022-03-04 07:52 UTC, ucyo commented on imktk/dataarray_methods/anomalies.py
> +    anomalies = dataarray.groupby("time.month") - climatology(dataarray)
Yes. You did not use the function `main`. Try `from imktk.dataarray_methods.climatology import main as climatology`

2022-03-04 08:16 UTC, fabrivelas commented
Hmm, I have to admit that I don’t understand :-)

> On 4 Mar 2022, at 08:52, ucyo ***@***.***> wrote:
> 
> 
> @ucyo commented on this pull request.
> 
> In imktk/dataarray_methods/anomalies.py <https://github.com/imk-toolkit/imk-toolkit/pull/60#discussion_r819338818>:
> 
> >  
>  
>  def main(dataarray):
>      """Return monthly anomalies for dataarray."""
>      assert isinstance(dataarray, xr.DataArray), "Input is not an xr.DataArray"
> -    climatology = dataarray.groupby("time.month").mean("time")
> -    anomalies = dataarray.groupby("time.month") - climatology
> +    anomalies = dataarray.groupby("time.month") - climatology(dataarray)
> Yes. You did not use the function main. Try from imktk.dataarray_methods.climatology import main as climatology
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/imk-toolkit/imk-toolkit/pull/60#discussion_r819338818>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEHP7MWGAON6RS6I6IRWPELU6G6NVANCNFSM5P2YXJ7A>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you authored the thread.
>

2022-03-04 08:19 UTC, ucyo commented
You are basically importing only the file and not the function

2022-03-04 08:25 UTC, fabrivelas commented
Sorry for being ignorant, how do I import the function?

> On 4 Mar 2022, at 09:19, ucyo ***@***.***> wrote:
> 
> 
> You are basically importing only the file and not the function
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/imk-toolkit/imk-toolkit/pull/60#issuecomment-1058938678>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEHP7MWVSRKCX2ETDRBOL6TU6HBQDANCNFSM5P2YXJ7A>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you authored the thread.
>

2022-03-04 08:28 UTC, ucyo commented
There is a Turkish saying:

> Do not give me fish, teach me how to fish myself

2022-03-04 08:30 UTC, fabrivelas commented
Ok, teach me :-)

> On 4 Mar 2022, at 09:29, ucyo ***@***.***> wrote:
> 
> 
> There is a Turkish saying:
> 
> Do not give me fish, teach me how to fish myself
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/imk-toolkit/imk-toolkit/pull/60#issuecomment-1058945664>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEHP7MXT7OWDY6WR74FYW63U6HCVFANCNFSM5P2YXJ7A>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you authored the thread.
>

2022-03-04 08:37 UTC, ucyo commented
1. `main` is nothing different than a normal function. 
2. You can see the possible submodules and functions of an object `obj` by using `dir(obj)`

2022-04-13 12:04 UTC, ucyo commented
Resolved with #85

2022-04-13 12:04 UTC, closed without merging