vapour_pres_liq method
imk-toolkit/imk-toolkit pull request #82
Opened 2022-04-01 05:38 UTC by NicBuettner

2022-04-05 09:43 UTC, ucyo requested changes
Very nice contribution. I love the definition of `T` as a variable. Perhaps we should adopt this in our template 😁

2022-04-05 09:43 UTC, ucyo commented on imktk/dataarray_methods/vapour_pres_liq.py
> +Murphy & Koop.
Do you have link to the paper? Even if it a commonly acknowledged method and obvious where to look for, it would be great to have a link to the paper where the function is defined

2022-04-05 09:43 UTC, ucyo commented on imktk/dataarray_methods/vapour_pres_liq.py
> +    assert isinstance(T, xr.DataArray), "Input is not an xr.DataArray"
In the module description it says that the method is only valid if the temperature is in the range of `(123; 232)`. What happens if any of the values is not within this range? Adding a check here would allow us to output a warning that the value range is not matching.

2022-04-05 09:43 UTC, ucyo commented on imktk/dataarray_methods/vapour_pres_liq.py
> +    )
I assume that all these constants have a specific meaning. It would be great if the calculation would represent them so the maintenance of the code is easier. We could first define the constants and then actually use them in the calculation

2022-04-06 09:45 UTC, NicBuettner commented on imktk/dataarray_methods/vapour_pres_liq.py
> +Murphy & Koop.
I've added a doi for the paper.

2022-04-06 09:47 UTC, NicBuettner commented on imktk/dataarray_methods/vapour_pres_liq.py
> +    assert isinstance(T, xr.DataArray), "Input is not an xr.DataArray"
I've added a min/max check for the temperature and a warning. I'm not sure if this is the most elegant way.

2022-04-06 09:48 UTC, NicBuettner commented on imktk/dataarray_methods/vapour_pres_liq.py
> +    )
These constants are actually fitting parameters, so I'm not sure if it would make sense to define them additionally.

2022-04-11 13:45 UTC, ucyo approved these changes

2022-04-11 13:45 UTC, merged